# Generated by Django 5.1.5 on 2025-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_picture',
            field=models.BinaryField(null=True, verbose_name='Зображення допису'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
