# Generated by Django 5.1.5 on 2025-04-06 17:17

from django.db import migrations, models
from django.core.files.base import ContentFile
import uuid

def move_binary_to_image(apps, schema_editor):
    BlogPost = apps.get_model('webapp', 'BlogPost')
    for obj in BlogPost.objects.all():
        if obj.post_picture:
            filename = f"{uuid.uuid4().hex}.jpg"
            obj.post_image.save(filename, ContentFile(obj.post_picture))
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_blogpost_last_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="post_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog_images/",
                verbose_name="Зображення допису",
            ),
        ),
        migrations.RunPython(move_binary_to_image)
        # migrations.RemoveField(
        #     model_name='BlogPost',
        #     name='post_picture',
        # ),
    ]
